{% set name = "cmip" %}
{% set version = "2.6.1" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2346e6d1435a4dc37c498a1beec03c1f290ed699603b8da30361bb475bb820b6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: http://mmb.irbbarcelona.org/gitlab/gelpi/CMIP/raw/master/dist/cmip.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
  run:

test:
  commands:
    - cmip -h

about:
  home: http://mmb.irbbarcelona.org/gitlab/gelpi/CMIP
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: CMIP Classical Molecular Interaction Potentials
  description: "The latest version of the classical molecular interaction potential (CMIP) has the abil- ity to predict the position of crystallographic waters in several proteins with great accuracy."
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
